Blog/Models/Article.cs
<<<<<<< HEAD
﻿using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
=======
﻿using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
>>>>>>> bb2f3aa44f68db192bd45cb5288d83367e83e90e

namespace Blog.Models
{
    public class Article
    {
<<<<<<< HEAD
        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        public string Title { get; set; }

        [Required]
=======

        private ICollection<Tag> tags;
        public Article()
        {
            this.tags = new HashSet<Tag>();
        }

        

        public Article(string authorId, string title, string content, int categoryId)
        {
            this.AuthorId = authorId;
            this.Title = title;
            this.Content = content;
            this.CategoryId = categoryId;
            this.tags = new HashSet<Tag>();
        }

        [Key]
        public int Id { get; set; }


        [Required]
        [StringLength(255)]
        public string Title { get; set; }

>>>>>>> bb2f3aa44f68db192bd45cb5288d83367e83e90e
        public string Content { get; set; }

        [ForeignKey("Author")]
        public string AuthorId { get; set; }

        public virtual ApplicationUser Author { get; set; }

<<<<<<< HEAD
=======
        // Every article should have categoryId
        [Required]
        [ForeignKey("Category")]
        public int CategoryId { get; set; }

        public virtual Category Category { get; set; }

        public virtual ICollection<Tag> Tags
        {
            //get; set;
            get { return this.tags; }
            set { this.tags = value; }
        }

>>>>>>> bb2f3aa44f68db192bd45cb5288d83367e83e90e
        public bool IsAuthor(string name)
        {
            return this.Author.UserName.Equals(name);
        }
<<<<<<< HEAD
    }
}
=======


    }
}
>>>>>>> bb2f3aa44f68db192bd45cb5288d83367e83e90e

Blog/Models/ArticleViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Blog.Models
{
    public class ArticleViewModel
    {
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        public string Title { get; set; }

<<<<<<< HEAD
        public string Content { get; set; }

        [Required]
        public string AuthorId { get; set; }
=======
        [Required]
        public string Content { get; set; }

        public string AuthorId { get; set; }

        [Required]
        [Display(Name = "Category")]
        public int CategoryId { get; set; }

        //public ICollection<Category> Categories { get; set; }

        public List<Category> Categories { get; set; }

        public string Tags { get; set; }
>>>>>>> bb2f3aa44f68db192bd45cb5288d83367e83e90e
    }
}

Blog/Controllers/ArticleController.cs
using Blog.Models;
<<<<<<< HEAD
using System.Data.Entity;
using System.Linq;
using System.Net;
=======
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
>>>>>>> bb2f3aa44f68db192bd45cb5288d83367e83e90e
using System.Web.Mvc;

namespace Blog.Controllers
{
    public class ArticleController : Controller
    {
<<<<<<< HEAD
        //
=======
>>>>>>> bb2f3aa44f68db192bd45cb5288d83367e83e90e
        // GET: Article
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        //
        // GET: Article/List
        public ActionResult List()
        {
<<<<<<< HEAD
            using (var database = new BlogDbContext())
            {
                var articles = database.Articles
                    .Include(a => a.Author)
=======

            using (var database = new BlogDbContext())
            {
                // Get articles from database
                var articles = database.Articles
                    .Include(a => a.Author)
                    .Include(a => a.Tags)
>>>>>>> bb2f3aa44f68db192bd45cb5288d83367e83e90e
                    .ToList();

                return View(articles);
            }
<<<<<<< HEAD
=======
            //return View();
>>>>>>> bb2f3aa44f68db192bd45cb5288d83367e83e90e
        }

        //
        // GET: Article/Details
        public ActionResult Details(int? id)
        {
<<<<<<< HEAD
            if (id == null)
=======
            if(id == null)
>>>>>>> bb2f3aa44f68db192bd45cb5288d83367e83e90e
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            using (var database = new BlogDbContext())
            {
<<<<<<< HEAD
                var article = database.Articles
                    .Where(a => a.Id == id)
                    .Include(a => a.Author)
=======
                // Get the article from database

                var article = database.Articles
                    .Where(a => a.Id == id)
                    .Include(a => a.Author)
                    .Include(a => a.Tags)
>>>>>>> bb2f3aa44f68db192bd45cb5288d83367e83e90e
                    .First();

                if (article == null)
                {
                    return HttpNotFound();
                }

                return View(article);
            }
<<<<<<< HEAD
=======

            
>>>>>>> bb2f3aa44f68db192bd45cb5288d83367e83e90e
        }

        //
        // GET: Article/Create
<<<<<<< HEAD
        [Authorize]
        public ActionResult Create()
        {
            return View();
=======
        [HttpGet]
        [Authorize]
        public ActionResult Create()
        {
            using (var database = new BlogDbContext())
            {
                var model = new ArticleViewModel();
                model.Categories = database.Categories
                    .OrderBy(c => c.Name)
                    .ToList();

                return View(model);
            }

>>>>>>> bb2f3aa44f68db192bd45cb5288d83367e83e90e
        }

        //
        // POST: Article/Create
        [HttpPost]
        [Authorize]
<<<<<<< HEAD
        public ActionResult Create(Article article)
        {
            if (ModelState.IsValid)
            {
                using (var database = new BlogDbContext())
                {
=======
        public ActionResult Create(ArticleViewModel model)
        {
            if(ModelState.IsValid)
            {
                using (var database = new BlogDbContext())
                {
                    // Get author id
>>>>>>> bb2f3aa44f68db192bd45cb5288d83367e83e90e
                    var authorId = database.Users
                        .Where(u => u.UserName == this.User.Identity.Name)
                        .First()
                        .Id;

<<<<<<< HEAD
                    article.AuthorId = authorId;

=======
                    var article = new Article(authorId, model.Title, model.Content, model.CategoryId);

                    // Set articles author
                    article.AuthorId = authorId;

                    this.SetArticleTags(article, model, database);

                    // Save article in DB
>>>>>>> bb2f3aa44f68db192bd45cb5288d83367e83e90e
                    database.Articles.Add(article);
                    database.SaveChanges();

                    return RedirectToAction("Index");
                }
            }

<<<<<<< HEAD
            return View(article);
=======
            return View(model);
>>>>>>> bb2f3aa44f68db192bd45cb5288d83367e83e90e
        }

        //
        // GET: Article/Delete
<<<<<<< HEAD
        [Authorize]
=======
>>>>>>> bb2f3aa44f68db192bd45cb5288d83367e83e90e
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
<<<<<<< HEAD
            
            using (var database = new BlogDbContext())
            {
                // Get article from database
                var article = database.Articles
                    .Where(a => a.Id == id)
                    .Include(a => a.Author)
                    .First();
=======

            using (var database = new BlogDbContext())
            {
                // Get article from database
                //var article = database.Articles
                //    .Where(a => a.Id == id)
                //    .Include(a => a.Author)
                //    .First();

                var article = database.Articles
                    .Include(a => a.Category)
                    .FirstOrDefault(a => a.Id == id);
>>>>>>> bb2f3aa44f68db192bd45cb5288d83367e83e90e

                if (!IsUserAuthorizedToEdit(article))
                {
                    return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
                }

<<<<<<< HEAD
                // Check if article exists
=======
                ViewBag.TagsString = string.Join(", ", article.Tags.Select(t => t.Name));
                // Check if article exist
>>>>>>> bb2f3aa44f68db192bd45cb5288d83367e83e90e
                if (article == null)
                {
                    return HttpNotFound();
                }

                // Pass article to view
                return View(article);
            }
        }

        //
        // POST: Article/Delete
<<<<<<< HEAD
        [HttpPost, Authorize]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmed(int? id)
        {
            if (id == null)
=======
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmed(int? id)
        {
            if(id==null)
>>>>>>> bb2f3aa44f68db192bd45cb5288d83367e83e90e
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            using (var database = new BlogDbContext())
            {
                // Get article from database
                var article = database.Articles
                    .Where(a => a.Id == id)
                    .Include(a => a.Author)
                    .First();

<<<<<<< HEAD
                // Check if article exists
=======
                // Check if article exist
>>>>>>> bb2f3aa44f68db192bd45cb5288d83367e83e90e
                if (article == null)
                {
                    return HttpNotFound();
                }

                // Delete article from database
                database.Articles.Remove(article);
                database.SaveChanges();

                // Redirect to index page
                return RedirectToAction("Index");
            }
<<<<<<< HEAD
=======
            
>>>>>>> bb2f3aa44f68db192bd45cb5288d83367e83e90e
        }

        //
        // GET: Article/Edit
<<<<<<< HEAD
        [Authorize]
=======
>>>>>>> bb2f3aa44f68db192bd45cb5288d83367e83e90e
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            using (var database = new BlogDbContext())
            {
                // Get article from the database
                var article = database.Articles
                    .Where(a => a.Id == id)
                    .First();

                if (!IsUserAuthorizedToEdit(article))
                {
                    return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
                }

<<<<<<< HEAD
                // Check if article exists
=======
                // Check if article exist
>>>>>>> bb2f3aa44f68db192bd45cb5288d83367e83e90e
                if (article == null)
                {
                    return HttpNotFound();
                }

                // Create the view model
                var model = new ArticleViewModel();
                model.Id = article.Id;
<<<<<<< HEAD
                model.AuthorId = article.AuthorId;
                model.Title = article.Title;
                model.Content = article.Content;

                // Show the editing view
=======
                model.Title = article.Title;
                model.Content = article.Content;
                model.CategoryId = article.CategoryId;
                model.Categories = database.Categories
                    .OrderBy(c => c.Name)
                    .ToList();

                model.Tags = string.Join(", ", article.Tags.Select(t => t.Name));

                //  Pass the view model to view
>>>>>>> bb2f3aa44f68db192bd45cb5288d83367e83e90e
                return View(model);
            }
        }

        //
        // POST: Article/Edit
        [HttpPost]
<<<<<<< HEAD
        [Authorize]
        public ActionResult Edit(ArticleViewModel model)
        {
            // Check if model state is valid
            if (ModelState.IsValid)
=======
        public ActionResult Edit(ArticleViewModel model)
        {
            // Check if model state is valid

Blog/Controllers/TagController.cs
using Blog.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Blog.Controllers
{
    public class TagController : Controller
    {
        // GET: Tag
        public ActionResult List(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            using (var database = new BlogDbContext())
            {
                // Get Articles from database
                var articles = database.Tags
                    .Include(t => t.Articles.Select(a => a.Tags))
                    .Include(t => t.Articles.Select(a => a.Author))
                    .FirstOrDefault(t => t.Id == id)
                    .Articles
                    .ToList();

                // Return the view
                return View(articles);
            }
        }
    }
}

Blog/Views/Article/Create.cshtml
<<<<<<< HEAD
﻿@model Blog.Models.Article
=======
﻿@model Blog.Models.ArticleViewModel
>>>>>>> bb2f3aa44f68db192bd45cb5288d83367e83e90e
@{
    ViewBag.Title = "Create";
}

<div class="container">
    <div class="well">
        <h2>Create Article</h2>
        @using (Html.BeginForm("Create", "Article", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary("", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(m => m.Title, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Content, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextAreaFor(m => m.Content, new { @class = "form-control", @rows = "7" })
                </div>
            </div>

            <div class="form-group">
<<<<<<< HEAD
=======
                @Html.LabelFor(m => m.CategoryId, new { @class = "col-sm-4 control-label" })
                <div class="dropdown col-sm-4">
                    @Html.DropDownListFor(m => m.CategoryId,
                        new SelectList(Model.Categories, "Id", "Name"),
                        new { @class = "btn btn-info col-sm-12" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Tags, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextBoxFor(m => m.Tags, new { @class = "form-control col-sm-4" })
                </div>
            </div>

            <div class="form-group">
>>>>>>> bb2f3aa44f68db192bd45cb5288d83367e83e90e
                <div class="col-sm-4 col-sm-offset-4">
                    @Html.ActionLink("Cancel", "Index", "Article", null, new { @class = "btn btn-default" })
                    <input type="submit" value="Create" class="btn btn-success" />
                </div>
            </div>
        }
    </div>
<<<<<<< HEAD
</div>
=======
</div>
>>>>>>> bb2f3aa44f68db192bd45cb5288d83367e83e90e

Blog/Views/Article/Delete.cshtml
@model Blog.Models.Article

@{
    ViewBag.Title = "Delete";
}

<div class="container">
    <div class="well">
        <h2>Delete Article</h2>
        @using (Html.BeginForm("Delete", "Article", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-group">
                @Html.LabelFor(m => m.Title, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextBoxFor(m => m.Title, new { @class = "form-control", @readonly = "readonly" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Content, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextAreaFor(m => m.Content, new { @class = "form-control", @readonly = "readonly", @rows = "7" })
                </div>
            </div>

            <div class="form-group">
<<<<<<< HEAD
=======
                @Html.LabelFor(m => m.Category, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextAreaFor(m => m.Category.Name, new { @class = "form-control", @readonly = "readonly", @rows = "1"})
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Category, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextBoxFor(m => m.Category.Name, new { @class = "form-control", @readonly = "readonly" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Tags, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextBox("tagsString", (object)ViewBag.TagsString, new { @class = "form-control", @readonly = "readonly" })
                </div>
            </div>

            <div class="form-group">
>>>>>>> bb2f3aa44f68db192bd45cb5288d83367e83e90e
                <div class="col-sm-4 col-sm-offset-4">
                    @Html.ActionLink("Cancel", "Index", "Article", null, new { @class = "btn btn-default" })
                    <input type="submit" value="Delete" class="btn btn-danger" />
                </div>
            </div>
        }
    </div>
<<<<<<< HEAD
</div>
=======
</div>
>>>>>>> bb2f3aa44f68db192bd45cb5288d83367e83e90e

Blog/Views/Article/Details.cshtml
@model Blog.Models.Article

@{
    ViewBag.Title = "Details";
}

<div class="container">
    <article>
        <header>
            <h2>
                @Model.Title
            </h2>
        </header>
        <p>
            @Model.Content
        </p>
        <small class="author">
            --author @Model.Author.FullName
        </small>
<<<<<<< HEAD
        <footer class="pull-right">
            @Html.ActionLink("Edit", "Edit", "Article", new { @id = Model.Id }, new { @class = "btn btn-success btn-xs" })
            @Html.ActionLink("Delete", "Delete", "Article", new { @id = Model.Id }, new { @class = "btn btn-danger btn-xs" })
            @Html.ActionLink("Back", "Index", "Article", null, new { @class = "btn btn-default btn-xs" })
=======
        <footer>
            <div class="pull-left">
                @foreach (var tag in Model.Tags)
                {
                    @Html.ActionLink(tag.Name, "List", "Tag", new { @id = tag.Id }, new { @class = "btn btn-default btn-xs" })
                }
            </div>
            
            <div>
                <small class="author pull-right">
                    --author @Model.Author.FullName
                </small>
            </div>

            <div class="pull-right">
                @if (User.IsInRole("Admin") || Model.IsAuthor(User.Identity.Name))
                {
                    @Html.ActionLink("Edit", "Edit", "Article", new { @id = Model.Id }, new { @class = "btn btn-success btn-xs" })
                    @Html.ActionLink("Delete", "Delete", "Article", new { @id = Model.Id }, new { @class = "btn btn-danger btn-xs" })
                }
                @Html.ActionLink("Back", "Index", "Article", null, new { @class = "btn btn-default btn-xs" })
            </div>
>>>>>>> bb2f3aa44f68db192bd45cb5288d83367e83e90e
        </footer>
    </article>
</div>
<hr />

Blog/Views/Article/Edit.cshtml
@model Blog.Models.ArticleViewModel

<<<<<<< HEAD
@{
=======
@{ 
>>>>>>> bb2f3aa44f68db192bd45cb5288d83367e83e90e
    ViewBag.Title = "Edit";
}

<div class="container">
    <div class="well">
        <h2>Edit Article</h2>
        @using (Html.BeginForm("Edit", "Article", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary()

            @Html.HiddenFor(m => m.Id)
            @Html.HiddenFor(m => m.AuthorId)

            <div class="form-group">
<<<<<<< HEAD
                @Html.LabelFor(m => m.Title, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
=======
                @Html.LabelFor(m => m.Title, new { @class = "control-label col-sm-4"})
                <div class="col-sm-4">
                    @Html.TextBoxFor(m => m.Title, new { @class = "form-control"})
>>>>>>> bb2f3aa44f68db192bd45cb5288d83367e83e90e
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Content, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextAreaFor(m => m.Content, new { @class = "form-control", @rows = "7" })
                </div>
            </div>

            <div class="form-group">
<<<<<<< HEAD
=======
                @Html.LabelFor(m => m.CategoryId, new { @class = "control-label col-sm-4" })
                <div class="dropdown col-sm-4">
                    @Html.DropDownListFor(m => m.CategoryId,
                        new SelectList(Model.Categories, "Id", "Name", Model.CategoryId),
                        new { @class = "btn btn-info col-sm-12" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Tags, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextBoxFor(m => m.Tags, new { @class = "form-control col-sm-4" })
                </div>
            </div>


            <div class="form-group">
>>>>>>> bb2f3aa44f68db192bd45cb5288d83367e83e90e
                <div class="col-sm-4 col-sm-offset-4">
                    @Html.ActionLink("Cancel", "Index", "Article", null, new { @class = "btn btn-default" })
                    <input type="submit" value="Edit" class="btn btn-success" />
                </div>
            </div>
        }
    </div>
<<<<<<< HEAD
</div>
=======
</div>
>>>>>>> bb2f3aa44f68db192bd45cb5288d83367e83e90e

Blog/Views/Article/List.cshtml
@model List<Blog.Models.Article>

@{
    ViewBag.Title = "List";
}

<div class="container">
    <div class="row">
        @foreach (var article in Model)
        {
            <div class="col-sm-6">
                <article>
                    <header>
                        <h2>
                            @Html.ActionLink(@article.Title, "Details", "Article", new { @id = article.Id }, null)
                        </h2>
                    </header>
                    <p>
                        @article.Content
                    </p>
                    <footer class="pull-right">
                        <small class="author">
                            --author @article.Author.FullName
                        </small>
                    </footer>
                </article>
            </div>
        }
    </div>
</div>
<hr />